services:
  backend:
    image: serba-native:latest
    container_name: serba-native-backend
    volumes:
      - D:\:/data
    ports:
      - "8080:8080"
    environment:
      JDBC_URL: jdbc:postgresql://serba-native-postgres:5432/serba
      DB_USERNAME: serba
      DB_PASSWORD: serba
    depends_on:
      - serba-postgres

  serba-postgres:
    image: postgres:15
    container_name: serba-native-postgres
    environment:
      POSTGRES_DB: serba
      POSTGRES_USER: serba
      POSTGRES_PASSWORD: serba
    restart: unless-stopped
