flyway:
  datasources:
    default:
      enabled: true

datasources:
  default:
    db-type: postgres
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:1111/serba
    username: serba
    password: serba

micronaut:
  application:
    name: serba
  server:
    port: 8080
    cors:
      enabled: true
      allowed-origins:
        - "http://localhost:5173"
      allowed-methods:
        - GET
        - POST
        - OPTIONS
        - PUT
        - DELETE
      allowed-headers:
        - Authorization
        - Content-Type
      allow-credentials: true
  security:
    enabled: true
    authentication: session
    redirect:
      enabled: false
    intercept-url-map:
      - pattern: /login
        access:
          - isAnonymous()   # allow anonymous access to /login
      - pattern: /**
        access:
          - isAuthenticated()  # protect all other routes  test:
    resources:
      enabled: false

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
